# Generated by Django 3.2.3 on 2021-08-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empmobnumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('emn', models.IntegerField()),
                ('edegn', models.CharField(max_length=30)),
                ('edept', models.CharField(max_length=20)),
                ('emandal', models.CharField(max_length=20)),
            ],
        ),
    ]
